#!/usr/bin/env bash
#this script build required libraries and copies into Fiji installation directory
FIJI_APP=ImageJ-linux64
UPDATE_SITE=P2E-IT4Innovations
mvn clean install dependency:copy-dependencies

DIR=`readlink -f $1`
cd hpc-workflow-manager-client/target/dependency
cp scp-java-client-*.jar jaxrpc-api-*.jar heappe-java-client-*.jar hpc-workflow-manager-heappe-adapter-*.jar $DIR/jars

cd ../../../hpc-workflow-manager-client/target/
cp hpc-workflow-manager-*[0-9T].jar $DIR/plugins
$DIR/$FIJI_APP --update upload-complete-site $UPDATE_SITE
