#!/usr/bin/env bash
#this script build required libraries and copies into Fiji installation directory
FIJI_APP=ImageJ-linux64
UPDATE_SITE=P2E-IT4Innovations
mvn clean install dependency:copy-dependencies

DIR=`readlink -f $1`
cd haas-spim-benchmark/target/dependency
cp java-scpclient-*.jar jaxrpc-api-*.jar haas-imagej-client-*.jar haas-java-client-*.jar $DIR/jars

cd ../../../haas-spim-benchmark/target/
cp haas-spim-benchmark-*[0-9T].jar $DIR/plugins
$DIR/$FIJI_APP --update upload-complete-site $UPDATE_SITE
